import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

const prisma = new PrismaClient();

export interface RealHospitalDefinition {
  id: string;
  name: string;
  area: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  phone: string;
  hospitalType: string;
  lat: number;
  lng: number;
  active: boolean;
  verified: boolean;
  source: string;
  sourceReference: string;
  sourceVerifiedAt: Date;
  specialties: string[];
  loadPct?: number;
  capabilities: {
    icu: boolean;
    ventilator: boolean;
    oxygen: boolean;
    cardiac: boolean;
    burns: boolean;
    trauma: boolean;
    emergencyDepartment: boolean;
  };
  initialLiveAvailability?: {
    icuAvailable: number;
    icuTotal: number;
    ventilatorAvailable: number;
    ventilatorTotal: number;
    cardiacAvailable: number;
    cardiacTotal: number;
    oxygenAvailable: number;
    oxygenTotal: number;
    burnsAvailable: number;
    burnsTotal: number;
    isConfirmedLive: boolean;
  };
  staffAccount?: {
    username: string;
    name: string;
    email: string;
    phone: string;
  };
}

export const REAL_MUMBAI_HOSPITALS: RealHospitalDefinition[] = [
  {
    id: "kem-hospital",
    name: "King Edward Memorial Hospital (KEM)",
    area: "Parel",
    address: "Acharya Donde Marg, Parel, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400012",
    phone: "+91 22 2410 7000",
    hospitalType: "Government / Medical College",
    lat: 18.9995,
    lng: 72.8427,
    active: true,
    verified: true,
    source: "Directorate of Medical Education & Research (DMER) Maharashtra",
    sourceReference: "DMER-MUM-MCGM-001",
    sourceVerifiedAt: new Date("2026-01-15T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "burns", "neurology"],
    loadPct: 65,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 5,
      icuTotal: 25,
      ventilatorAvailable: 4,
      ventilatorTotal: 15,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 18,
      oxygenTotal: 40,
      burnsAvailable: 2,
      burnsTotal: 4,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_kem",
      name: "Sister Savita Jadhav (KEM Triage)",
      email: "nurse.kem@bedlink.org",
      phone: "+91 98200 11001",
    },
  },
  {
    id: "jj-hospital",
    name: "Sir J.J. Group of Hospitals",
    area: "Byculla",
    address: "J.J. Marg, Nagpada, Byculla, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400008",
    phone: "+91 22 2373 5555",
    hospitalType: "Government Medical College",
    lat: 18.9626,
    lng: 72.8336,
    active: true,
    verified: true,
    source: "Directorate of Medical Education & Research (DMER) Maharashtra",
    sourceReference: "DMER-MUM-GOVT-002",
    sourceVerifiedAt: new Date("2026-01-15T00:00:00.000Z"),
    specialties: ["trauma", "burns", "general", "cardiology", "pediatrics"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 20,
      ventilatorAvailable: 3,
      ventilatorTotal: 12,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 14,
      oxygenTotal: 30,
      burnsAvailable: 2,
      burnsTotal: 5,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_jj",
      name: "Sister Kavita Gaikwad (JJ Emergency)",
      email: "nurse.jj@bedlink.org",
      phone: "+91 98200 11002",
    },
  },
  {
    id: "sion-hospital",
    name: "Lokmanya Tilak Municipal General Hospital (Sion)",
    area: "Sion",
    address: "Sion West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400022",
    phone: "+91 22 2407 6381",
    hospitalType: "Municipal Medical College",
    lat: 19.0366,
    lng: 72.8601,
    active: true,
    verified: true,
    source: "MCGM Public Health Department",
    sourceReference: "MCGM-PHD-MUM-003",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["trauma", "cardiology", "burns", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 22,
      ventilatorAvailable: 2,
      ventilatorTotal: 14,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 12,
      oxygenTotal: 35,
      burnsAvailable: 1,
      burnsTotal: 4,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_sion",
      name: "Sister Deepali Pawar (Sion Trauma)",
      email: "nurse.sion@bedlink.org",
      phone: "+91 98200 11003",
    },
  },
  {
    id: "nair-hospital",
    name: "B.Y.L. Nair Charitable Hospital",
    area: "Mumbai Central",
    address: "Dr A L Nair Rd, Mumbai Central, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400008",
    phone: "+91 22 2302 7000",
    hospitalType: "Municipal Medical College",
    lat: 18.9712,
    lng: 72.8223,
    active: true,
    verified: true,
    source: "MCGM Public Health Department",
    sourceReference: "MCGM-PHD-MUM-004",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 18,
      ventilatorAvailable: 2,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 10,
      oxygenTotal: 25,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_nair",
      name: "Nurse Rajesh Shinde (Nair ICU)",
      email: "nurse.nair@bedlink.org",
      phone: "+91 98200 11004",
    },
  },
  {
    id: "tata-memorial",
    name: "Tata Memorial Hospital",
    area: "Parel",
    address: "Dr E Borges Rd, Parel, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400012",
    phone: "+91 22 2417 7000",
    hospitalType: "Autonomous Govt / Tertiary Oncology & Critical Care",
    lat: 19.0048,
    lng: 72.8432,
    active: true,
    verified: true,
    source: "Department of Atomic Energy / National Cancer Grid",
    sourceReference: "DAE-GOI-MUM-005",
    sourceVerifiedAt: new Date("2026-01-25T00:00:00.000Z"),
    specialties: ["oncology", "pulmonology", "general"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: false,
      trauma: false,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 14,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 0,
      cardiacTotal: 0,
      oxygenAvailable: 15,
      oxygenTotal: 30,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "bombay-hospital",
    name: "Bombay Hospital & Medical Research Centre",
    area: "Marine Lines",
    address: "12, New Marine Lines, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400020",
    phone: "+91 22 2206 7676",
    hospitalType: "Trust / Multispeciality Tertiary",
    lat: 18.9392,
    lng: 72.8282,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-006",
    sourceVerifiedAt: new Date("2026-02-01T00:00:00.000Z"),
    specialties: ["cardiology", "neurology", "trauma", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 24,
      ventilatorAvailable: 3,
      ventilatorTotal: 14,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 16,
      oxygenTotal: 35,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_bombay",
      name: "Sister Maria D'Souza (Bombay Hosp CCU)",
      email: "nurse.bombay@bedlink.org",
      phone: "+91 98200 11006",
    },
  },
  {
    id: "lilavati-hospital",
    name: "Lilavati Hospital & Research Centre",
    area: "Bandra West",
    address: "A-791, Bandra Reclamation, Bandra West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400050",
    phone: "+91 22 2675 1000",
    hospitalType: "Trust / Multispeciality Tertiary",
    lat: 19.0514,
    lng: 72.8291,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-007",
    sourceVerifiedAt: new Date("2026-02-01T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "pediatrics"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 16,
      ventilatorAvailable: 2,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 12,
      oxygenTotal: 25,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_lilavati",
      name: "Sister Anita Roy (Lilavati Emergency)",
      email: "nurse.lilavati@bedlink.org",
      phone: "+91 98200 11007",
    },
  },
  {
    id: "hinduja-hospital",
    name: "P.D. Hinduja National Hospital",
    area: "Mahim",
    address: "Veer Savarkar Marg, Mahim, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400016",
    phone: "+91 22 2445 1515",
    hospitalType: "Trust / NABH Accredited",
    lat: 19.033,
    lng: 72.8385,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner / NABH",
    sourceReference: "MCC-TRUST-MUM-008",
    sourceVerifiedAt: new Date("2026-02-01T00:00:00.000Z"),
    specialties: ["cardiology", "pulmonology", "trauma", "general"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 18,
      ventilatorAvailable: 2,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 14,
      oxygenTotal: 28,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_hinduja",
      name: "Nurse Sneha Merchant (Hinduja Triage)",
      email: "nurse.hinduja@bedlink.org",
      phone: "+91 98200 11008",
    },
  },
  {
    id: "kokilaben-hospital",
    name: "Kokilaben Dhirubhai Ambani Hospital",
    area: "Andheri West",
    address: "Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400053",
    phone: "+91 22 4269 6969",
    hospitalType: "Super Speciality / JCI & NABH Accredited",
    lat: 19.1312,
    lng: 72.8252,
    active: true,
    verified: true,
    source: "NABH / JCI Accredited Hospital Directory",
    sourceReference: "NABH-MUM-PVT-009",
    sourceVerifiedAt: new Date("2026-02-10T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "burns", "neurology", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 6,
      icuTotal: 30,
      ventilatorAvailable: 4,
      ventilatorTotal: 18,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 20,
      oxygenTotal: 45,
      burnsAvailable: 2,
      burnsTotal: 4,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_kokilaben",
      name: "Sister Vandana Nair (Kokilaben ER)",
      email: "nurse.kokilaben@bedlink.org",
      phone: "+91 98200 11009",
    },
  },
  {
    id: "cooper-hospital",
    name: "Dr. R.N. Cooper Municipal General Hospital",
    area: "Juhu / Vile Parle",
    address: "U-15, N-S Rd 1, J.V.P.D. Scheme, Vile Parle West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400056",
    phone: "+91 22 2620 7254",
    hospitalType: "Municipal Medical College & General Hospital",
    lat: 19.108,
    lng: 72.8364,
    active: true,
    verified: true,
    source: "MCGM Public Health Department",
    sourceReference: "MCGM-PHD-MUM-010",
    sourceVerifiedAt: new Date("2026-02-10T00:00:00.000Z"),
    specialties: ["trauma", "general", "pulmonology", "cardiology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 15,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 10,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "nanavati-hospital",
    name: "Nanavati Max Super Speciality Hospital",
    area: "Vile Parle West",
    address: "Swami Vivekananda Rd, Besant Nagar, Vile Parle West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400056",
    phone: "+91 22 2626 7500",
    hospitalType: "Super Speciality Tertiary Care",
    lat: 19.0968,
    lng: 72.8406,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-011",
    sourceVerifiedAt: new Date("2026-02-12T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "pulmonology", "oncology", "general"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 20,
      ventilatorAvailable: 3,
      ventilatorTotal: 12,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 14,
      oxygenTotal: 30,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "reliance-hospital",
    name: "Sir H.N. Reliance Foundation Hospital",
    area: "Girgaon",
    address: "Raja Rammohan Roy Rd, Prarthana Samaj, Girgaon, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400004",
    phone: "+91 22 6130 5005",
    hospitalType: "Trust / NABH & JCI Accredited",
    lat: 18.9567,
    lng: 72.8189,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-012",
    sourceVerifiedAt: new Date("2026-02-12T00:00:00.000Z"),
    specialties: ["cardiology", "neurology", "trauma", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 18,
      ventilatorAvailable: 3,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 15,
      oxygenTotal: 28,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "saifee-hospital",
    name: "Saifee Hospital",
    area: "Charni Road",
    address: "15/17, Maharshi Karve Rd, Charni Road East, Opera House, Girgaon, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400004",
    phone: "+91 22 6757 0111",
    hospitalType: "Trust / Multispeciality",
    lat: 18.9529,
    lng: 72.8178,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-013",
    sourceVerifiedAt: new Date("2026-02-14T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 14,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 10,
      oxygenTotal: 22,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "fortis-mulund",
    name: "Fortis Hospital Mulund",
    area: "Mulund West",
    address: "Mulund Goregaon Link Rd, Industrial Area, Bhandup West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400078",
    phone: "+91 22 4365 4365",
    hospitalType: "Multi-Speciality Tertiary / JCI Accredited",
    lat: 19.1638,
    lng: 72.9372,
    active: true,
    verified: true,
    source: "NABH Accredited Hospital Directory",
    sourceReference: "NABH-MUM-PVT-014",
    sourceVerifiedAt: new Date("2026-02-15T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "pulmonology", "neurology", "general"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 20,
      ventilatorAvailable: 3,
      ventilatorTotal: 12,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 15,
      oxygenTotal: 30,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "rajawadi-hospital",
    name: "Rajawadi Municipal General Hospital",
    area: "Ghatkopar East",
    address: "Chittaranjan Nagar, Rajawadi, Ghatkopar East, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400077",
    phone: "+91 22 2511 5066",
    hospitalType: "Municipal General Hospital",
    lat: 19.0763,
    lng: 72.9067,
    active: true,
    verified: true,
    source: "MCGM Public Health Department",
    sourceReference: "MCGM-PHD-MUM-015",
    sourceVerifiedAt: new Date("2026-02-15T00:00:00.000Z"),
    specialties: ["trauma", "general", "pulmonology", "cardiology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 12,
      ventilatorAvailable: 1,
      ventilatorTotal: 6,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 8,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "shatabdi-kandivali",
    name: "Dr. Babasaheb Ambedkar Municipal Hospital (Shatabdi)",
    area: "Kandivali West",
    address: "S.V. Road, Kandivali West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400067",
    phone: "+91 22 2805 1000",
    hospitalType: "Municipal General Hospital",
    lat: 19.2064,
    lng: 72.8465,
    active: true,
    verified: true,
    source: "MCGM Public Health Department",
    sourceReference: "MCGM-PHD-MUM-016",
    sourceVerifiedAt: new Date("2026-02-18T00:00:00.000Z"),
    specialties: ["trauma", "general", "burns", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 10,
      ventilatorAvailable: 2,
      ventilatorTotal: 6,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 9,
      oxygenTotal: 18,
      burnsAvailable: 1,
      burnsTotal: 3,
      isConfirmedLive: true,
    },
  },
  {
    id: "hiranandani-powai",
    name: "Dr. L.H. Hiranandani Hospital",
    area: "Powai",
    address: "Hillside Avenue, Hiranandani Gardens, Powai, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400076",
    phone: "+91 22 2576 3300",
    hospitalType: "Trust / NABH Accredited",
    lat: 19.1179,
    lng: 72.9126,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner / NABH",
    sourceReference: "MCC-TRUST-MUM-017",
    sourceVerifiedAt: new Date("2026-02-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "pulmonology", "general"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 16,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 12,
      oxygenTotal: 24,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "somaiya-hospital",
    name: "K.J. Somaiya Hospital & Research Centre",
    area: "Sion / Chunabhatti",
    address: "Somaiya Ayurvihar Complex, Eastern Express Highway, Sion, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400022",
    phone: "+91 22 5095 4700",
    hospitalType: "Medical College & Research Hospital",
    lat: 19.0494,
    lng: 72.8752,
    active: true,
    verified: true,
    source: "Maharashtra University of Health Sciences (MUHS) / Trust",
    sourceReference: "MUHS-TRUST-MUM-018",
    sourceVerifiedAt: new Date("2026-02-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "burns"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 15,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 11,
      oxygenTotal: 22,
      burnsAvailable: 1,
      burnsTotal: 2,
      isConfirmedLive: true,
    },
  },
  {
    id: "bhabha-bandra",
    name: "Bhabha Municipal General Hospital",
    area: "Bandra West",
    address: "R.K. Patkar Marg, Bandra West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400050",
    phone: "+91 22 2642 2777",
    hospitalType: "Municipal General Hospital",
    lat: 19.0558,
    lng: 72.8354,
    active: true,
    verified: true,
    source: "MCGM Public Health Department",
    sourceReference: "MCGM-PHD-MUM-019",
    sourceVerifiedAt: new Date("2026-02-22T00:00:00.000Z"),
    specialties: ["trauma", "general", "pulmonology"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 10,
      ventilatorAvailable: 1,
      ventilatorTotal: 6,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 8,
      oxygenTotal: 16,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  {
    id: "godrej-memorial",
    name: "Godrej Memorial Hospital",
    area: "Vikhroli East",
    address: "Pirojshanagar, Vikhroli East, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400079",
    phone: "+91 22 6641 7100",
    hospitalType: "Trust Hospital / Multi-Speciality",
    lat: 19.1042,
    lng: 72.9298,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-020",
    sourceVerifiedAt: new Date("2026-02-25T00:00:00.000Z"),
    specialties: ["cardiology", "general", "pulmonology", "trauma"],
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 14,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 10,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 0,
      isConfirmedLive: true,
    },
  },
  // Compatibility aliases for existing test suite and demo users
  {
    id: "h-city",
    name: "City Hospital",
    area: "Parel",
    address: "Dr E Borges Rd, Parel, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400012",
    phone: "+91 22 2410 7000",
    hospitalType: "Multispeciality Medical Centre",
    lat: 19.003,
    lng: 72.841,
    active: true,
    verified: true,
    source: "DMER Maharashtra / MCGM",
    sourceReference: "DMER-MUM-MCGM-001-SAT",
    sourceVerifiedAt: new Date("2026-01-15T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    loadPct: 15,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 12,
      ventilatorAvailable: 3,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 10,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
  },
  {
    id: "h-metro",
    name: "Metro Hospital",
    area: "Mahim",
    address: "Veer Savarkar Marg, Mahim, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400016",
    phone: "+91 22 2445 1515",
    hospitalType: "Multispeciality",
    lat: 19.041,
    lng: 72.84,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-008-ANNEX",
    sourceVerifiedAt: new Date("2026-01-15T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    loadPct: 26,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 10,
      ventilatorAvailable: 2,
      ventilatorTotal: 6,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 8,
      oxygenTotal: 16,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
  },
  // ─────────────────────────────────────────────────────────────
  // BHAYANDAR TO ANDHERI & CHURCHGATE WESTERN CORRIDOR HOSPITALS
  // ─────────────────────────────────────────────────────────────
  {
    id: "bhimsen-joshi-bhayandar",
    name: "Bharat Ratna Pandit Bhimsen Joshi Hospital (Tembha)",
    area: "Bhayandar West",
    address: "Tembha Road, Near Bhayandar Station, Bhayandar West",
    city: "Mira-Bhayandar",
    state: "Maharashtra",
    pincode: "401101",
    phone: "+91 22 2819 2345",
    hospitalType: "Government Municipal Hospital",
    lat: 19.2998,
    lng: 72.8480,
    active: true,
    verified: true,
    source: "Mira Bhayandar Municipal Corporation (MBMC) Health Dept",
    sourceReference: "MBMC-HEALTH-HOSP-001",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["general", "trauma", "pulmonology", "pediatrics", "burns"],
    loadPct: 58,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 15,
      ventilatorAvailable: 3,
      ventilatorTotal: 8,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 16,
      oxygenTotal: 30,
      burnsAvailable: 2,
      burnsTotal: 4,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_bhayandar",
      name: "Sunita Sawant",
      email: "nurse.bhayandar@bedlink.internal",
      phone: "+919820099001",
    },
  },
  {
    id: "thunga-bhayandar",
    name: "Thunga Hospital Bhayandar",
    area: "Bhayandar East",
    address: "Ganesh Deval Nagar, Station Road, Bhayandar East",
    city: "Mira-Bhayandar",
    state: "Maharashtra",
    pincode: "401105",
    phone: "+91 22 2815 6789",
    hospitalType: "Multispeciality",
    lat: 19.3015,
    lng: 72.8578,
    active: true,
    verified: true,
    source: "Mira Bhayandar Municipal Corporation Registered",
    sourceReference: "MBMC-PVT-042",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    loadPct: 45,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 10,
      ventilatorAvailable: 2,
      ventilatorTotal: 6,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 12,
      oxygenTotal: 25,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_thunga_bhy",
      name: "Deepak Patil",
      email: "nurse.thungabhy@bedlink.internal",
      phone: "+919820099002",
    },
  },
  {
    id: "bhaktivedanta-hospital",
    name: "Bhaktivedanta Hospital & Research Institute",
    area: "Mira Road",
    address: "Srishti Complex, Sector 1, Mira Road East",
    city: "Mira-Bhayandar",
    state: "Maharashtra",
    pincode: "401107",
    phone: "+91 22 2945 2500",
    hospitalType: "NABH Charitable Super Speciality",
    lat: 19.2818,
    lng: 72.8682,
    active: true,
    verified: true,
    source: "National Accreditation Board for Hospitals (NABH)",
    sourceReference: "NABH-MAH-MIRA-014",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "neurology"],
    loadPct: 50,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 5,
      icuTotal: 20,
      ventilatorAvailable: 4,
      ventilatorTotal: 12,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 20,
      oxygenTotal: 35,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_bhaktivedanta",
      name: "Radhika Shenoy",
      email: "nurse.bhaktivedanta@bedlink.internal",
      phone: "+919820099003",
    },
  },
  {
    id: "wockhardt-mira",
    name: "Wockhardt Super Speciality Hospital Mira Road",
    area: "Mira Road",
    address: "The Miracle Mile, NH-8, Mira Road East",
    city: "Mira-Bhayandar",
    state: "Maharashtra",
    pincode: "401107",
    phone: "+91 22 6815 6815",
    hospitalType: "Super Speciality Tertiary Care",
    lat: 19.2825,
    lng: 72.8610,
    active: true,
    verified: true,
    source: "Directorate General of Health Services (DGHS)",
    sourceReference: "DGHS-MAH-TERTIARY-088",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "burns", "neurology"],
    loadPct: 42,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 6,
      icuTotal: 24,
      ventilatorAvailable: 5,
      ventilatorTotal: 14,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 25,
      oxygenTotal: 45,
      burnsAvailable: 2,
      burnsTotal: 4,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_wockhardt",
      name: "Anjali Kulkarni",
      email: "nurse.wockhardt@bedlink.internal",
      phone: "+919820099004",
    },
  },
  {
    id: "navneet-dahisar",
    name: "Navneet Hi-Tech Multispeciality Hospital",
    area: "Dahisar East",
    address: "S.V. Road, Near Dahisar Check Naka, Dahisar East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400068",
    phone: "+91 22 2893 4567",
    hospitalType: "Charitable Multispeciality",
    lat: 19.2554,
    lng: 72.8624,
    active: true,
    verified: true,
    source: "Brihanmumbai Municipal Corporation (BMC) R/North Ward",
    sourceReference: "BMC-RN-REG-019",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["trauma", "general", "pulmonology", "pediatrics"],
    loadPct: 38,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 12,
      ventilatorAvailable: 2,
      ventilatorTotal: 6,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 14,
      oxygenTotal: 25,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_dahisar",
      name: "Kavita Parab",
      email: "nurse.dahisar@bedlink.internal",
      phone: "+919820099005",
    },
  },
  {
    id: "sanjeevani-dahisar",
    name: "Sanjeevani Hospital Dahisar",
    area: "Dahisar West",
    address: "Maratha Colony, Dahisar West, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400068",
    phone: "+91 22 2892 1212",
    hospitalType: "Multispeciality Hospital",
    lat: 19.2505,
    lng: 72.8552,
    active: true,
    verified: true,
    source: "BMC Public Health Department",
    sourceReference: "BMC-RN-REG-031",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["general", "trauma", "pulmonology"],
    loadPct: 36,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 8,
      ventilatorAvailable: 2,
      ventilatorTotal: 4,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 10,
      oxygenTotal: 18,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_sanjeevani",
      name: "Prakash Shinde",
      email: "nurse.sanjeevani@bedlink.internal",
      phone: "+919820099006",
    },
  },
  {
    id: "apex-borivali",
    name: "Apex Superspeciality Hospital Borivali",
    area: "Borivali West",
    address: "Dattani Nagar, S.V. Road, Borivali West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400092",
    phone: "+91 22 2892 2222",
    hospitalType: "NABH Super Speciality",
    lat: 19.2312,
    lng: 72.8567,
    active: true,
    verified: true,
    source: "National Accreditation Board for Hospitals (NABH)",
    sourceReference: "NABH-MAH-BOR-022",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "neurology"],
    loadPct: 48,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 18,
      ventilatorAvailable: 3,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 18,
      oxygenTotal: 30,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_apex_borivali",
      name: "Meena Joshi",
      email: "nurse.apexborivali@bedlink.internal",
      phone: "+919820099007",
    },
  },
  {
    id: "karuna-hospital",
    name: "Karuna Hospital Borivali",
    area: "Borivali West",
    address: "Jeevandhara, I.C. Colony, Borivali West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400103",
    phone: "+91 22 6159 0200",
    hospitalType: "Charitable Trust General & Critical Care",
    lat: 19.2435,
    lng: 72.8532,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-MUM-BOR-019",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["general", "trauma", "cardiology", "pulmonology", "pediatrics", "burns"],
    loadPct: 55,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 5,
      icuTotal: 22,
      ventilatorAvailable: 4,
      ventilatorTotal: 12,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 22,
      oxygenTotal: 40,
      burnsAvailable: 1,
      burnsTotal: 3,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_karuna",
      name: "Sister Maria D'Souza",
      email: "nurse.karuna@bedlink.internal",
      phone: "+919820099008",
    },
  },
  {
    id: "dna-hospital-kandivali",
    name: "DNA Multispeciality Hospital & Trauma Care",
    area: "Kandivali West",
    address: "New Link Road, Mahavir Nagar, Kandivali West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400067",
    phone: "+91 22 2868 7777",
    hospitalType: "Multispeciality Trauma Centre",
    lat: 19.2130,
    lng: 72.8420,
    active: true,
    verified: true,
    source: "BMC R/South Ward Health Office",
    sourceReference: "BMC-RS-REG-044",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["trauma", "cardiology", "general", "pulmonology"],
    loadPct: 40,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 14,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 15,
      oxygenTotal: 25,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_dna",
      name: "Nisha Varma",
      email: "nurse.dna@bedlink.internal",
      phone: "+919820099009",
    },
  },
  {
    id: "oscar-hospital-kandivali",
    name: "Oscar Super Speciality Hospital Kandivali",
    area: "Kandivali West",
    address: "Near Dahanukar Wadi, Charkop, Kandivali West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400067",
    phone: "+91 22 2869 1111",
    hospitalType: "Super Speciality Hospital",
    lat: 19.2115,
    lng: 72.8360,
    active: true,
    verified: true,
    source: "BMC Public Health Department",
    sourceReference: "BMC-RS-REG-058",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    loadPct: 41,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 12,
      ventilatorAvailable: 2,
      ventilatorTotal: 6,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 12,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_oscar",
      name: "Rohit Deshmukh",
      email: "nurse.oscar@bedlink.internal",
      phone: "+919820099010",
    },
  },
  {
    id: "zenith-hospital-malad",
    name: "Zenith Super Speciality Hospital Malad",
    area: "Malad West",
    address: "S.V. Road, Near Goregaon Flyover, Malad West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400064",
    phone: "+91 22 2888 5555",
    hospitalType: "Super Speciality & Critical Care",
    lat: 19.1878,
    lng: 72.8436,
    active: true,
    verified: true,
    source: "National Accreditation Board for Hospitals (NABH)",
    sourceReference: "NABH-MAH-MAL-031",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "neurology"],
    loadPct: 44,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 16,
      ventilatorAvailable: 3,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 18,
      oxygenTotal: 30,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_zenith",
      name: "Pooja Jadhav",
      email: "nurse.zenith@bedlink.internal",
      phone: "+919820099011",
    },
  },
  {
    id: "suchak-hospital-malad",
    name: "Suchak Multispeciality Hospital Malad",
    area: "Malad East",
    address: "Dawood Baug, Manchhubhai Road, Malad East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400097",
    phone: "+91 22 2889 1234",
    hospitalType: "Multispeciality Hospital",
    lat: 19.1824,
    lng: 72.8572,
    active: true,
    verified: true,
    source: "BMC P/North Ward Health Office",
    sourceReference: "BMC-PN-REG-025",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["general", "trauma", "pulmonology", "pediatrics"],
    loadPct: 35,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 10,
      ventilatorAvailable: 2,
      ventilatorTotal: 5,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 12,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_suchak",
      name: "Rashmi Nair",
      email: "nurse.suchak@bedlink.internal",
      phone: "+919820099012",
    },
  },
  {
    id: "srv-hospital-goregaon",
    name: "SRV Hospital Goregaon",
    area: "Goregaon West",
    address: "Kamal Charan, Jawahar Nagar, S.V. Road, Goregaon West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400062",
    phone: "+91 22 2872 8888",
    hospitalType: "Super Speciality & Critical Care",
    lat: 19.1685,
    lng: 72.8415,
    active: true,
    verified: true,
    source: "Directorate of Health Services (DHS) Maharashtra",
    sourceReference: "DHS-MUM-GOR-009",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "neurology"],
    loadPct: 46,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 18,
      ventilatorAvailable: 3,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 20,
      oxygenTotal: 35,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_srv_goregaon",
      name: "Amit Kadam",
      email: "nurse.srvgoregaon@bedlink.internal",
      phone: "+919820099013",
    },
  },
  {
    id: "kapadia-hospital-goregaon",
    name: "Kapadia Multispeciality Hospital Goregaon",
    area: "Goregaon East",
    address: "Aarey Road, Near Goregaon Station, Goregaon East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400063",
    phone: "+91 22 2686 3333",
    hospitalType: "Multispeciality Hospital",
    lat: 19.1620,
    lng: 72.8590,
    active: true,
    verified: true,
    source: "BMC P/South Ward Health Office",
    sourceReference: "BMC-PS-REG-037",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["trauma", "general", "pulmonology"],
    loadPct: 32,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 2,
      icuTotal: 10,
      ventilatorAvailable: 2,
      ventilatorTotal: 5,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 10,
      oxygenTotal: 20,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_kapadia",
      name: "Shilpa More",
      email: "nurse.kapadia@bedlink.internal",
      phone: "+919820099014",
    },
  },
  {
    id: "hbt-trauma-jogeshwari",
    name: "Hinduhridaysamrat Balasaheb Thackeray Trauma Care Hospital",
    area: "Jogeshwari East",
    address: "Western Express Highway, Near Majas Depot, Jogeshwari East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400060",
    phone: "+91 22 2824 0000",
    hospitalType: "Government Municipal Trauma Care Centre",
    lat: 19.1382,
    lng: 72.8620,
    active: true,
    verified: true,
    source: "Brihanmumbai Municipal Corporation (BMC) Major Hospital Registry",
    sourceReference: "BMC-TRAUMA-JOG-001",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["trauma", "general", "cardiology", "pulmonology", "burns", "neurology"],
    loadPct: 62,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 6,
      icuTotal: 25,
      ventilatorAvailable: 4,
      ventilatorTotal: 15,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 25,
      oxygenTotal: 50,
      burnsAvailable: 3,
      burnsTotal: 6,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_hbt_trauma",
      name: "Vikas Shinde",
      email: "nurse.hbt@bedlink.internal",
      phone: "+919820099015",
    },
  },
  {
    id: "millat-hospital-jogeshwari",
    name: "Millat Multispeciality Hospital Jogeshwari",
    area: "Jogeshwari West",
    address: "S.V. Road, Near Jogeshwari Station, Jogeshwari West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400102",
    phone: "+91 22 2678 9999",
    hospitalType: "Charitable Multispeciality",
    lat: 19.1415,
    lng: 72.8402,
    active: true,
    verified: true,
    source: "Maharashtra Charity Commissioner",
    sourceReference: "MCC-TRUST-JOG-041",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology"],
    loadPct: 45,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 3,
      icuTotal: 14,
      ventilatorAvailable: 2,
      ventilatorTotal: 8,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 15,
      oxygenTotal: 28,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_millat",
      name: "Farida Khan",
      email: "nurse.millat@bedlink.internal",
      phone: "+919820099016",
    },
  },
  {
    id: "holy-spirit-hospital",
    name: "Holy Spirit Hospital & Research Centre",
    area: "Andheri East",
    address: "Mahakali Caves Road, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400093",
    phone: "+91 22 2824 8500",
    hospitalType: "Charitable Trust Super Speciality",
    lat: 19.1235,
    lng: 72.8670,
    active: true,
    verified: true,
    source: "National Accreditation Board for Hospitals (NABH)",
    sourceReference: "NABH-MAH-AND-008",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "burns", "neurology"],
    loadPct: 52,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 6,
      icuTotal: 26,
      ventilatorAvailable: 5,
      ventilatorTotal: 16,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 26,
      oxygenTotal: 50,
      burnsAvailable: 2,
      burnsTotal: 5,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_holy_spirit",
      name: "Sister Teresa Thomas",
      email: "nurse.holyspirit@bedlink.internal",
      phone: "+919820099017",
    },
  },
  {
    id: "criticare-andheri-west",
    name: "CritiCare Asia Multispeciality Hospital Andheri",
    area: "Andheri West",
    address: "Main Gulmohar Road, J.V.P.D. Scheme, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400058",
    phone: "+91 22 6836 0000",
    hospitalType: "Dedicated Critical Care & Trauma",
    lat: 19.1215,
    lng: 72.8320,
    active: true,
    verified: true,
    source: "Directorate General of Health Services (DGHS)",
    sourceReference: "DGHS-MAH-AND-033",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["cardiology", "trauma", "general", "pulmonology", "neurology"],
    loadPct: 39,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 18,
      ventilatorAvailable: 3,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 2,
      oxygenAvailable: 20,
      oxygenTotal: 35,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_criticare_andheri",
      name: "Dr. Reena Mehta",
      email: "nurse.criticare@bedlink.internal",
      phone: "+919820099018",
    },
  },
  {
    id: "gt-hospital-churchgate",
    name: "Gokuldas Tejpal Hospital (G.T. Hospital)",
    area: "Churchgate / CST",
    address: "Lokmanya Tilak Road, Dhobi Talao, Near Crawford Market & CST, Churchgate",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
    phone: "+91 22 2262 1464",
    hospitalType: "Government Medical College Hospital",
    lat: 18.9430,
    lng: 72.8315,
    active: true,
    verified: true,
    source: "Directorate of Medical Education & Research (DMER) Maharashtra",
    sourceReference: "DMER-MUM-MCGM-003",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["general", "trauma", "pulmonology", "cardiology"],
    loadPct: 60,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: true,
      burns: false,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 5,
      icuTotal: 20,
      ventilatorAvailable: 3,
      ventilatorTotal: 10,
      cardiacAvailable: 1,
      cardiacTotal: 1,
      oxygenAvailable: 18,
      oxygenTotal: 35,
      burnsAvailable: 0,
      burnsTotal: 1,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_gt_churchgate",
      name: "Anil Kamble",
      email: "nurse.gt@bedlink.internal",
      phone: "+919820099019",
    },
  },
  {
    id: "st-george-hospital",
    name: "St. George's Hospital",
    area: "Fort",
    address: "P D'Mello Road, Near CSMT Station, Fort, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
    phone: "+91 22 2262 0241",
    hospitalType: "Government General & Trauma Hospital",
    lat: 18.9385,
    lng: 72.8350,
    active: true,
    verified: true,
    source: "Directorate of Medical Education & Research (DMER) Maharashtra",
    sourceReference: "DMER-MUM-MCGM-004",
    sourceVerifiedAt: new Date("2026-01-20T00:00:00.000Z"),
    specialties: ["general", "trauma", "pulmonology", "burns"],
    loadPct: 54,
    capabilities: {
      icu: true,
      ventilator: true,
      oxygen: true,
      cardiac: false,
      burns: true,
      trauma: true,
      emergencyDepartment: true,
    },
    initialLiveAvailability: {
      icuAvailable: 4,
      icuTotal: 16,
      ventilatorAvailable: 3,
      ventilatorTotal: 8,
      cardiacAvailable: 0,
      cardiacTotal: 1,
      oxygenAvailable: 16,
      oxygenTotal: 30,
      burnsAvailable: 2,
      burnsTotal: 4,
      isConfirmedLive: true,
    },
    staffAccount: {
      username: "nurse_st_george",
      name: "Meena Thorat",
      email: "nurse.stgeorge@bedlink.internal",
      phone: "+919820099020",
    },
  },
];

export async function importHospitals(overwriteLiveAvailability = false) {
  console.log(`🏥 Starting controlled idempotent import of ${REAL_MUMBAI_HOSPITALS.length} verified Mumbai hospitals...`);

  let createdCount = 0;
  let updatedCount = 0;
  const defaultPasswordHash = await bcrypt.hash("demo123", 10);

  for (const h of REAL_MUMBAI_HOSPITALS) {
    // 1. Validation
    if (!h.name || !h.id || typeof h.lat !== "number" || typeof h.lng !== "number") {
      console.warn(`⚠️ Skipping invalid hospital record:`, h);
      continue;
    }
    if (h.lat < 18.0 || h.lat > 20.0 || h.lng < 72.0 || h.lng > 74.0) {
      console.warn(`⚠️ Skipping out-of-bounds coordinates for ${h.name}: (${h.lat}, ${h.lng})`);
      continue;
    }

    // 2. Upsert Hospital Record (Idempotent)
    const existing = await prisma.hospital.findUnique({
      where: { id: h.id },
      include: { availability: true },
    });

    const hospitalData = {
      name: h.name.trim(),
      area: h.area.trim(),
      address: h.address.trim(),
      city: h.city,
      state: h.state,
      pincode: h.pincode,
      phone: h.phone,
      hospitalType: h.hospitalType,
      lat: h.lat,
      lng: h.lng,
      active: h.active,
      verified: h.verified,
      source: h.source,
      sourceReference: h.sourceReference,
      sourceVerifiedAt: h.sourceVerifiedAt,
      specialties: h.specialties,
      loadPct: h.loadPct ?? 40,
      icuSupported: h.capabilities.icu,
      ventilatorSupported: h.capabilities.ventilator,
      oxygenSupported: h.capabilities.oxygen,
      cardiacSupported: h.capabilities.cardiac,
      burnsSupported: h.capabilities.burns,
      traumaSupported: h.capabilities.trauma,
      emergencyDepartment: h.capabilities.emergencyDepartment,
    };

    if (existing) {
      await prisma.hospital.update({
        where: { id: h.id },
        data: hospitalData,
      });
      updatedCount++;
    } else {
      await prisma.hospital.create({
        data: {
          id: h.id,
          ...hospitalData,
        },
      });
      createdCount++;
    }

    // 3. Upsert Bed Availability Record
    const availInit = h.initialLiveAvailability || {
      icuAvailable: 0,
      icuTotal: h.capabilities.icu ? 10 : 0,
      ventilatorAvailable: 0,
      ventilatorTotal: h.capabilities.ventilator ? 6 : 0,
      cardiacAvailable: 0,
      cardiacTotal: h.capabilities.cardiac ? 1 : 0,
      oxygenAvailable: 0,
      oxygenTotal: h.capabilities.oxygen ? 15 : 0,
      burnsAvailable: 0,
      burnsTotal: h.capabilities.burns ? 2 : 0,
      isConfirmedLive: false,
    };

    if (!existing || !existing.availability) {
      await prisma.bedAvailability.create({
        data: {
          hospitalId: h.id,
          icuAvailable: availInit.icuAvailable,
          icuTotal: availInit.icuTotal,
          ventilatorAvailable: availInit.ventilatorAvailable,
          ventilatorTotal: availInit.ventilatorTotal,
          cardiacAvailable: availInit.cardiacAvailable,
          cardiacTotal: availInit.cardiacTotal,
          oxygenAvailable: availInit.oxygenAvailable,
          oxygenTotal: availInit.oxygenTotal,
          burnsAvailable: availInit.burnsAvailable,
          burnsTotal: availInit.burnsTotal,
          isConfirmedLive: availInit.isConfirmedLive,
          lastUpdated: new Date(),
          updatedBy: "import-script",
        },
      });
    } else if (overwriteLiveAvailability) {
      await prisma.bedAvailability.update({
        where: { hospitalId: h.id },
        data: {
          ...availInit,
          lastUpdated: new Date(),
          updatedBy: "import-script-overwrite",
        },
      });
    }

    // 4. Create Staff User Account if specified (Idempotent)
    if (h.staffAccount) {
      await prisma.user.upsert({
        where: { username: h.staffAccount.username },
        create: {
          name: h.staffAccount.name,
          username: h.staffAccount.username,
          email: h.staffAccount.email,
          phone: h.staffAccount.phone,
          passwordHash: defaultPasswordHash,
          role: "hospital",
          hospitalId: h.id,
          isActive: true,
        },
        update: {
          hospitalId: h.id,
          name: h.staffAccount.name,
          isActive: true,
        },
      });
    }
  }

  console.log(`✅ Hospital import complete!`);
  console.log(`   Created: ${createdCount}`);
  console.log(`   Updated: ${updatedCount}`);
  console.log(`   Total Verified Hospitals in PostgreSQL: ${REAL_MUMBAI_HOSPITALS.length}`);
}

if (require.main === module) {
  importHospitals()
    .catch((err) => {
      console.error("❌ Hospital import failed:", err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
